# Generated by Django 5.0.6 on 2024-06-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_intg', '0003_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='2ed07e', max_length=6),
        ),
    ]
