# Generated by Django 5.0.6 on 2024-06-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_intg', '0003_alter_customuser_email_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='3f5be8', max_length=6),
        ),
    ]
