# Generated by Django 5.0.6 on 2024-06-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_intg', '0005_remove_progress_in_progress_remove_progress_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='jours_rev',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='766f2d', max_length=6),
        ),
    ]
