# Generated by Django 5.0.6 on 2024-07-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_intg', '0016_progress_demi_journee_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='predh',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='81bf10', max_length=6),
        ),
    ]
