# Generated by Django 4.2.13 on 2024-06-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_intg', '0023_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='4d5ce1', max_length=6),
        ),
    ]
