# Generated by Django 5.0.6 on 2024-06-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_intg', '0025_alter_otptoken_otp_code_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='4a3292', max_length=6),
        ),
    ]
